export const recipes = [
  { name: "Scrambled Eggs", ingredients: ["eggs", "butter", "salt"] },
  { name: "Cheese Omelette", ingredients: ["eggs", "cheese", "butter", "salt"] },
  { name: "Pancakes", ingredients: ["flour", "eggs", "milk", "butter", "sugar"] },
  { name: "French Toast", ingredients: ["bread", "eggs", "milk", "cinnamon", "butter"] },
  { name: "Grilled Cheese", ingredients: ["bread", "cheese", "butter"] },
  { name: "Tomato Soup", ingredients: ["tomatoes", "onion", "garlic", "olive oil", "salt"] },
  { name: "Garlic Pasta", ingredients: ["pasta", "garlic", "olive oil", "parmesan"] },
  { name: "Spaghetti Marinara", ingredients: ["pasta", "tomatoes", "garlic", "olive oil", "basil"] },
  { name: "Caprese Salad", ingredients: ["tomatoes", "mozzarella", "basil", "olive oil"] },
  { name: "Guacamole", ingredients: ["avocados", "lime", "onion", "salt", "cilantro"] },
  { name: "Bean Burrito", ingredients: ["tortillas", "beans", "rice", "cheese", "salsa"] },
  { name: "Fried Rice", ingredients: ["rice", "eggs", "soy sauce", "peas", "carrots", "onion"] },
  { name: "Chicken Stir Fry", ingredients: ["chicken", "soy sauce", "garlic", "ginger", "carrots", "rice"] },
  { name: "Roast Chicken", ingredients: ["chicken", "lemon", "garlic", "butter", "salt"] },
  { name: "Mashed Potatoes", ingredients: ["potatoes", "butter", "milk", "salt"] },
  { name: "Baked Potato", ingredients: ["potatoes", "butter", "cheese", "sour cream"] },
  { name: "Banana Smoothie", ingredients: ["bananas", "milk", "honey", "yogurt"] },
  { name: "Oatmeal", ingredients: ["oats", "milk", "honey", "cinnamon"] },
  { name: "Peanut Butter Toast", ingredients: ["bread", "peanut butter", "bananas"] },
  { name: "Greek Salad", ingredients: ["tomatoes", "cucumber", "feta", "olives", "onion", "olive oil"] },
];
